ALTER TABLE `User`
  ADD COLUMN `profileBackgroundBlur` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `profileThemePreference` ENUM('SYSTEM', 'DARK', 'LIGHT') NOT NULL DEFAULT 'SYSTEM',
  ADD COLUMN `profileDefaultView` ENUM('CARD', 'TILE', 'GROUPED_BY_GAME') NOT NULL DEFAULT 'CARD',
  ADD COLUMN `profileGroupGames` BOOLEAN NOT NULL DEFAULT false;
